name: Docker vulnerability scan
description: Runs a vulnerability scan on the provided Docker image using Trivy and uploads the results to GitHub Security
inputs:
  docker-image:
    description: Docker image to scan
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker vulnerability scan
      uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac # tag=v0.7.1
      with:
        image-ref: ${{ inputs.docker-image }}
        format: 'github'
        output: 'dependency-results.sbom.json'
        github-pat: ${{ secrets.GITHUB_TOKEN }}
