name: Docker vulnerability scan
description: Runs a vulnerability scan on the provided Docker image using Trivy and uploads the results to GitHub Security
inputs:
  docker-image:
    description: Docker image to scan
    required: true

runs:
  using: "composite"
  steps:
    - name: Docker vulnerability scan
      uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac # tag=v0.7.1
      with:
        image-ref: ${{ inputs.docker-image }}
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'

    - name: Upload Docker vulnerability scan results
      uses: github/codeql-action/upload-sarif@ec3cf9c605b848da5f1e41e8452719eb1ccfb9a6 # tag=v2.1.29
      with:
        sarif_file: 'trivy-results.sarif'
