name: Docker dependency scan
description: Generates an SBOM for Docker images and uploads it to the GitHub dependency submission API
inputs:
  docker-image:
    description: Docker image to scan
    required: true
  github-pat:
    description: Personal access token used to upload the SBOM
    required: true    

runs:
  using: "composite"
  steps:
    - name: Docker dependency scan
      uses: aquasecurity/trivy-action@d63413b0a4a4482237085319f7f4a1ce99a8f2ac # tag=v0.7.1
      with:
        image-ref: ${{ inputs.docker-image }}
        format: 'github'
        output: 'dependency-results.sbom.json'
        github-pat: ${{ inputs.github-pat }}
