apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scan-files
  description: File scanning for CDS Platform products
  labels:
    license: MIT
spec:
  type: service
  lifecycle: experimental
  owner: group:cds-snc/internal-sre
  domain: site-reliability-engineering
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: scan-files-api
  description: API for the Scan Files Service
spec:
  type: openapi
  lifecycle: experimental
  owner: group:cds-snc/internal-sre
  domain: site-reliability-engineering
  definition: 
    $json: https://scan-files.alpha.canada.ca/openapi.json
  
