apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scan-files
  description: File scanning for CDS Platform products
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: group:cds-snc/platform-core-services
  domain: site-reliability-engineering
