"""rename checksum table

Revision ID: bca456ecde47
Revises: 693ead1304c2
Create Date: 2022-06-28 21:49:44.550338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bca456ecde47"
down_revision = "693ead1304c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scans", sa.Column("checksum", sa.String(), nullable=True))
    op.drop_column("scans", "sha256")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scans", sa.Column("sha256", sa.String(), autoincrement=False, nullable=True)
    )
    op.drop_column("scans", "checksum")
    # ### end Alembic commands ###
