test_case = '' # Run all tests by default; otherwise run user specified test
.PHONY: dev fmt install lint migrations test fmt-ci lint-ci build install-dev load-test

build: ;

dev: ;

fmt:
	yarn format:write

install:
	yarn install

install-dev: ;
	
lint:
	yarn lint

lint-ci:
	yarn lint

load-test: ;

migrations: ;

test:
	yarn test

fmt-ci:
	yarn format:check