name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - api/requirements.txt
      - .github/workflows/generate_sbom.yml
  push:
    branches:
      - main
    paths:
      - api/requirements.txt
      - .github/workflows/generate_sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@496f79b604b24dcbc905f22eb1abb7398566b1ec
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: scan-files/api
          project_type: python
          project_version: main
          working_directory: api
