name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - api/requirements.txt
      - .github/workflows/generate_sbom.yml
  push:
    branches:
      - main
    paths:
      - api/requirements.txt
      - .github/workflows/generate_sbom.yml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate api SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@43971382a09f23dc7c60b19d3aba9c1ab1c70216
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: scan-files/api
          project_type: python
          working_directory: api
