name: Integration test production

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Deploy Lambda Docker images to production"
      - "Terraform apply production"
    types:
      - completed

env:
  API_TOKEN: ${{ secrets.PRODUCTION_API_AUTH_TOKEN }}
  BUCKET_NAME: scan-files-production-integration-test

permissions:
  id-token: write
  contents: read

jobs:
  integration-test-production:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        url:
          - https://scan-files.alpha.canada.ca
          - https://sync.scan-files.alpha.canada.ca   

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@4fc4975a852c8cd99761e2de1f4ba73402e44dd9 # v4.0.3
        with:
          role-to-assume: arn:aws:iam::806545929748:role/scan-files-apply
          role-session-name: IntegrationTest
          aws-region: ca-central-1

      - name: Generate unique filename
        run: echo "FILENAME=scan.$(uuidgen).json" >> $GITHUB_ENV

      - name: Async test - upload test file
        run: aws s3 cp .github/workflows/assets/scan.json s3://${{ env.BUCKET_NAME }}/${{ env.FILENAME }}

      - name: Async test - wait for scan
        run: |
          COUNTER=0
          while true; do
            CHECKSUM="$(aws s3api get-object-tagging --bucket ${{ env.BUCKET_NAME }} --key ${{ env.FILENAME }} --output text | grep 'av-checksum' || true)"
            if [ "$CHECKSUM" != "" ]; then
              break
            fi
            
            COUNTER=$((COUNTER+1))
            if [ $COUNTER -gt 10 ]; then
              echo "💩 Async scan timed out"
              exit 1
            fi

            sleep 5
          done

      - name: Async test - expected verdict
        run: |
          VERDICT=$(aws s3api get-object-tagging \
            --bucket ${{ env.BUCKET_NAME }} \
            --key ${{ env.FILENAME }} \
            --query "TagSet[?Key=='av-status']" | jq -r '.[0].Value')
          if [ "$VERDICT" != "clean" ]; then
            echo "💩 Async unexpected verdict: $VERDICT"
            exit 1
          fi

      - name: Sync test - expected verdict
        run: |
          VERDICT=$(curl --silent --request POST "${{ matrix.url }}/clamav" \
            --header "Authorization: ${{ env.API_TOKEN }}" \
            --header "Content-Type: multipart/form-data" \
            --form "ignore_cache=True" \
            --form "file=@.github/workflows/assets/scan.json" | jq -r .verdict)
          if [ "$VERDICT" != "clean" ]; then
            echo "💩 Sync unexpected verdict: $VERDICT"
            exit 1
          fi

      - name: Slack message on failure
        if: failure()
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Integration test failed: <https://github.com/cds-snc/scan-files/actions/workflows/integration_test_production.yml|Integration test production>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SCAN_FILES_PROD_OPS_WEBHOOK }}
