name: "Terraform security scan"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/terraform-security-scan.yml"
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/terraform-security-scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf # tag=v12.1347.0
        with:
          config_file: terragrunt/.checkov.yml
          directory: terragrunt/aws
          framework: terraform
          output_format: cli
          quiet: true
          soft_fail: false
