
name: "Terraform security scan"

on:
  push:
    branches:
      - main
    paths:
      - "terragrunt/**"
      - ".github/workflows/terraform-security-scan.yml"      
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/terraform-security-scan.yml"

jobs:
  terraform-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkov security scan
        uses: bridgecrewio/checkov-action@d259454a31835b99ea6cf9aa1c2d08190f2f65c9 # latest as of Sept 9, 2021
        with:
          directory: terragrunt/aws
          framework: terraform
          output_format: cli
          soft_fail: false
