name: "Terraform plan production"
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/tf_plan_production.yml"
env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.0.3
  TERRAGRUNT_VERSION: 0.31.1
  CONFTEST_VERSION: 0.27.0
  TF_VAR_api_auth_token: ${{ secrets.PRODUCTION_API_AUTH_TOKEN }}
  TF_VAR_aws_org_id: ${{ secrets.AWS_ORG_ID }}
  TF_VAR_rds_password: ${{ secrets.PRODUCTION_RDS_PASSWORD }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: api
          - module: hosted_zone
          - module: s3_scan_object
          - module: scan_queue

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2 # tag=v1.6.1
        with:
          role-to-assume: arn:aws:iam::806545929748:role/OIDCGithubWorkflowRole
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@dce0ba2ac808e5c2b3499c8073adef25aaa559f3 # tag=v2.0.8
        with:
          comment-delete: true
          comment-title: Plan for ${{ matrix.module }}
          directory: ./terragrunt/env/production/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
